name: Build Test

on:
  push:
    branches: [ master, build-test ]
  pull_request:
    branches: [ master ]
  # run weekly to verify latest jadx snapshot version
  schedule:
    - cron: "22 2 * * 2"
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build
        run: ./gradlew build
